language: java
jdk:
  - openjdk8
cache:
  directories:
    - ~/.m2

install: true
script: mvn -B --global-toolchains travis-maven-toolchain.xml clean install -DskipTests &&
        mvn -B --global-toolchains travis-maven-toolchain.xml -pl :org.eclipse.birt.core.tests integration-test
before_cache:
  - rm -r ~/.m2/repository/org/eclipse/birt
  - rm -r ~/.m2/repository/.cache/tycho
